"""
Feature Engineering Module for Time-Series Forecasting

Constructs historical lag features, rolling statistics (means and standard deviations),
and price changes without introducing lookahead data leakage.
"""

import pandas as pd
import numpy as np


def create_lag_features(df: pd.DataFrame, lags: list[int] = [1, 2, 3, 5, 10, 20]) -> pd.DataFrame:
    """
    Generate historical lag features for the target 'close' price.

    Parameters:
    -----------
    df : pd.DataFrame
        DataFrame with 'close' column.
    lags : list[int]
        List of lag steps (e.g. [1, 2, 3, 5, 10, 20]).

    Returns:
    --------
    pd.DataFrame
        DataFrame with added lag feature columns.
    """
    df_feat = df.copy()
    for lag in lags:
        df_feat[f"lag_{lag}"] = df_feat["close"].shift(lag)
    return df_feat


def create_rolling_features(df: pd.DataFrame, windows: list[int] = [5, 10, 20]) -> pd.DataFrame:
    """
    Generate rolling mean and rolling standard deviation features.
    Uses shift(1) to strictly avoid data leakage of target close at time t.

    Parameters:
    -----------
    df : pd.DataFrame
        DataFrame with 'close' column.
    windows : list[int]
        List of window sizes (e.g. [5, 10, 20]).

    Returns:
    --------
    pd.DataFrame
        DataFrame with added rolling feature columns.
    """
    df_feat = df.copy()

    # Shift by 1 first so today's actual close is never included in the historical window
    past_close = df_feat["close"].shift(1)

    for w in windows:
        df_feat[f"rolling_mean_{w}"] = past_close.rolling(window=w).mean()
        df_feat[f"rolling_std_{w}"] = past_close.rolling(window=w).std()

    return df_feat


def create_return_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generate historical price change, percentage change, and daily return features.
    Shifted by 1 to eliminate data leakage.

    Parameters:
    -----------
    df : pd.DataFrame
        DataFrame with 'close' column.

    Returns:
    --------
    pd.DataFrame
        DataFrame with added price return features.
    """
    df_feat = df.copy()

    past_close = df_feat["close"].shift(1)
    df_feat["price_change"] = past_close.diff()
    df_feat["pct_change"] = past_close.pct_change()
    df_feat["daily_return"] = past_close.pct_change()

    return df_feat


def build_all_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Full feature pipeline combining lag features, rolling features, and returns.

    Parameters:
    -----------
    df : pd.DataFrame
        Cleaned dataframe.

    Returns:
    --------
    pd.DataFrame
        Dataframe containing all engineered features.
    """
    df_feat = create_lag_features(df, lags=[1, 2, 3, 5, 10, 20])
    df_feat = create_rolling_features(df_feat, windows=[5, 10, 20])
    df_feat = create_return_features(df_feat)

    return df_feat


def prepare_feature_matrix(df_features: pd.DataFrame) -> pd.DataFrame:
    """
    Safely drop initial rows containing NaN values generated by lag/rolling windows.

    Parameters:
    -----------
    df_features : pd.DataFrame
        Engineered dataframe.

    Returns:
    --------
    pd.DataFrame
        Cleaned feature matrix ready for training.
    """
    df_prepared = df_features.dropna().reset_index(drop=True)
    return df_prepared


if __name__ == "__main__":
    from pathlib import Path
    from data_preprocessing import load_raw_data, clean_and_sort_data

    root_dir = Path(__file__).resolve().parent.parent
    raw_df = load_raw_data(root_dir / "data" / "HistoricalQuotes.csv")
    clean_df = clean_and_sort_data(raw_df)

    feat_df = build_all_features(clean_df)
    prep_df = prepare_feature_matrix(feat_df)

    print("--- Feature Engineering Test Successful ---")
    print(f"Original rows: {len(clean_df)}, Prepared feature rows: {len(prep_df)}")
    feature_cols = [c for c in prep_df.columns if c not in ["date", "close", "open", "high", "low", "volume"]]
    print(f"Engineered features count: {len(feature_cols)}")
    print(f"Feature columns: {feature_cols}")
